start cmd.exe /C cfn2dsl -t AWSCloudFormer.template -o AWSCloudFormer.rb &
start cmd.exe /C cfn2dsl -t AutoScalingKeepAtNSample.template -o AutoScalingKeepAtNSample.rb &
start cmd.exe /C cfn2dsl -t AutoScalingMultiAZSample.template -o AutoScalingMultiAZSample.rb
start cmd.exe /C cfn2dsl -t AutoScalingMultiAZWithNotifications.template -o AutoScalingMultiAZWithNotifications.rb
start cmd.exe /C cfn2dsl -t AutoScalingRollingUpdates.template -o AutoScalingRollingUpdates.rb
start cmd.exe /C cfn2dsl -t CloudFrontMultiOriginWithBeanstalkApp.template -o CloudFrontMultiOriginWithBeanstalkApp.rb
start cmd.exe /C cfn2dsl -t CloudFront_MultiOrigin.template -o CloudFront_MultiOrigin.rb
start cmd.exe /C cfn2dsl -t CloudFront_S3.template -o CloudFront_S3.rb
start cmd.exe /C cfn2dsl -t Drupal_Multi_AZ.template -o Drupal_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t Drupal_Simple.template -o Drupal_Simple.rb
start cmd.exe /C cfn2dsl -t Drupal_Single_Instance.template -o Drupal_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Drupal_Single_Instance_With_RDS.template -o Drupal_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t DynamoDB_Table.template -o DynamoDB_Table.rb
start cmd.exe /C cfn2dsl -t EBS_Snapshot_On_Delete.template -o EBS_Snapshot_On_Delete.rb
start cmd.exe /C cfn2dsl -t EC2ChooseAMI.template -o EC2ChooseAMI.rb
start cmd.exe /C cfn2dsl -t EC2InstanceSample.template -o EC2InstanceSample.rb
start cmd.exe /C cfn2dsl -t EC2InstanceWithEBSVolumeConditionalIOPs.template -o EC2InstanceWithEBSVolumeConditionalIOPs.rb
start cmd.exe /C cfn2dsl -t EC2InstanceWithSecurityGroupSample.template -o EC2InstanceWithSecurityGroupSample.rb
start cmd.exe /C cfn2dsl -t EC2WebSiteSample.template -o EC2WebSiteSample.rb
start cmd.exe /C cfn2dsl -t EC2WithEBSPIOPs.template -o EC2WithEBSPIOPs.rb
start cmd.exe /C cfn2dsl -t EC2WithEBSSample.template -o EC2WithEBSSample.rb
start cmd.exe /C cfn2dsl -t EC2WithMetadata.template -o EC2WithMetadata.rb
start cmd.exe /C cfn2dsl -t EC2_Instance_With_Block_Device_Mapping.template -o EC2_Instance_With_Block_Device_Mapping.rb
start cmd.exe /C cfn2dsl -t EC2_Instance_With_Ephemeral_Drives.template -o EC2_Instance_With_Ephemeral_Drives.rb
start cmd.exe /C cfn2dsl -t EC2_Untargeted_Launch_with_EBS_Volume.template -o EC2_Untargeted_Launch_with_EBS_Volume.rb
start cmd.exe /C cfn2dsl -t EIP_With_Association.template -o EIP_With_Association.rb
start cmd.exe /C cfn2dsl -t ELBSample.template -o ELBSample.rb
start cmd.exe /C cfn2dsl -t ELBStickinessSample.template -o ELBStickinessSample.rb
start cmd.exe /C cfn2dsl -t ELBWithLockedDownAutoScaledInstances.template -o ELBWithLockedDownAutoScaledInstances.rb
start cmd.exe /C cfn2dsl -t ELBWithLockedDownEC2Instances.template -o ELBWithLockedDownEC2Instances.rb
start cmd.exe /C cfn2dsl -t ELBZoneApex.template -o ELBZoneApex.rb
start cmd.exe /C cfn2dsl -t ElastiCache.template -o ElastiCache.rb
start cmd.exe /C cfn2dsl -t ElastiCache_Redis.template -o ElastiCache_Redis.rb
start cmd.exe /C cfn2dsl -t Elastic-Beanstalk-in-VPC.template -o Elastic-Beanstalk-in-VPC.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalk.template -o ElasticBeanstalk.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalkSample.template -o ElasticBeanstalkSample.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalkSampleWithRoute53.template -o ElasticBeanstalkSampleWithRoute53.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalk_Nodejs_Sample.template -o ElasticBeanstalk_Nodejs_Sample.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalk_PHP_Sample.template -o ElasticBeanstalk_PHP_Sample.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalk_Ruby_Sample.template -o ElasticBeanstalk_Ruby_Sample.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalk_Simple.template -o ElasticBeanstalk_Simple.rb
start cmd.exe /C cfn2dsl -t ElasticBeanstalk_Windows_Sample.template -o ElasticBeanstalk_Windows_Sample.rb
start cmd.exe /C cfn2dsl -t Gollum_Simple.template -o Gollum_Simple.rb
start cmd.exe /C cfn2dsl -t Gollum_Single_Instance.template -o Gollum_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Gollum_Single_Instance_With_EBS_Volume.template -o Gollum_Single_Instance_With_EBS_Volume.rb
start cmd.exe /C cfn2dsl -t IAM_Policies_SNS_Publish_To_SQS.template -o IAM_Policies_SNS_Publish_To_SQS.rb
start cmd.exe /C cfn2dsl -t IAM_Policies_for_S3.template -o IAM_Policies_for_S3.rb
start cmd.exe /C cfn2dsl -t IAM_Users_Groups_and_Policies.template -o IAM_Users_Groups_and_Policies.rb
start cmd.exe /C cfn2dsl -t Insoshi_Multi_AZ.template -o Insoshi_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t Insoshi_Simple.template -o Insoshi_Simple.rb
start cmd.exe /C cfn2dsl -t Insoshi_Single_Instance.template -o Insoshi_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Insoshi_Single_Instance_With_RDS.template -o Insoshi_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t Joomla!_Multi_AZ.template -o Joomla!_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t Joomla!_Simple.template -o Joomla!_Simple.rb
start cmd.exe /C cfn2dsl -t Joomla!_Single_Instance.template -o Joomla!_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Joomla!_Single_Instance_With_RDS.template -o Joomla!_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t LAMP_Multi_AZ.template -o LAMP_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t LAMP_Simple.template -o LAMP_Simple.rb
start cmd.exe /C cfn2dsl -t LAMP_Single_Instance.template -o LAMP_Single_Instance.rb
start cmd.exe /C cfn2dsl -t LAMP_Single_Instance_With_RDS.template -o LAMP_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t MineCraft_Server.template -o MineCraft_Server.rb
start cmd.exe /C cfn2dsl -t MonitorEC2AndEBS.template -o MonitorEC2AndEBS.rb
start cmd.exe /C cfn2dsl -t Mutually_Referencing_EC2_Security_Groups.template -o Mutually_Referencing_EC2_Security_Groups.rb
start cmd.exe /C cfn2dsl -t Parameter_Validate.template -o Parameter_Validate.rb
start cmd.exe /C cfn2dsl -t RDSDatabaseWithOptionalReadReplica.template -o RDSDatabaseWithOptionalReadReplica.rb
start cmd.exe /C cfn2dsl -t RDS_MySQL_55.template -o RDS_MySQL_55.rb
start cmd.exe /C cfn2dsl -t RDS_MySQL_55_With_Tags.template -o RDS_MySQL_55_With_Tags.rb
start cmd.exe /C cfn2dsl -t RDS_Oracle.template -o RDS_Oracle.rb
start cmd.exe /C cfn2dsl -t RDS_PIOPS.template -o RDS_PIOPS.rb
start cmd.exe /C cfn2dsl -t RDS_Snapshot_On_Delete.template -o RDS_Snapshot_On_Delete.rb
start cmd.exe /C cfn2dsl -t RDS_VPC.template -o RDS_VPC.rb
start cmd.exe /C cfn2dsl -t RDS_Version.template -o RDS_Version.rb
start cmd.exe /C cfn2dsl -t RDS_with_DBParameterGroup.template -o RDS_with_DBParameterGroup.rb
start cmd.exe /C cfn2dsl -t Rails_Multi_AZ.template -o Rails_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t Rails_Simple.template -o Rails_Simple.rb
start cmd.exe /C cfn2dsl -t Rails_Single_Instance.template -o Rails_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Rails_Single_Instance_With_RDS.template -o Rails_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t Redmine_Multi_AZ.template -o Redmine_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t Redmine_Simple.template -o Redmine_Simple.rb
start cmd.exe /C cfn2dsl -t Redmine_Single_Instance.template -o Redmine_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Redmine_Single_Instance_With_RDS.template -o Redmine_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t Route53_A.template -o Route53_A.rb
start cmd.exe /C cfn2dsl -t Route53_CNAME.template -o Route53_CNAME.rb
start cmd.exe /C cfn2dsl -t Route53_RoundRobin.template -o Route53_RoundRobin.rb
start cmd.exe /C cfn2dsl -t S3Bucket_Auth_1.template -o S3Bucket_Auth_1.rb
start cmd.exe /C cfn2dsl -t S3Bucket_Auth_2.template -o S3Bucket_Auth_2.rb
start cmd.exe /C cfn2dsl -t S3Bucket_Lockdown_to_IAM_User.template -o S3Bucket_Lockdown_to_IAM_User.rb
start cmd.exe /C cfn2dsl -t S3Bucket_SourceAuth.template -o S3Bucket_SourceAuth.rb
start cmd.exe /C cfn2dsl -t S3_Bucket.template -o S3_Bucket.rb
start cmd.exe /C cfn2dsl -t S3_Bucket_With_Tags.template -o S3_Bucket_With_Tags.rb
start cmd.exe /C cfn2dsl -t S3_Website_Bucket_With_Retain_On_Delete.template -o S3_Website_Bucket_With_Retain_On_Delete.rb
start cmd.exe /C cfn2dsl -t S3_Website_With_CloudFront_Distribution.template -o S3_Website_With_CloudFront_Distribution.rb
start cmd.exe /C cfn2dsl -t S3_With_CloudFront_Distribution.template -o S3_With_CloudFront_Distribution.rb
start cmd.exe /C cfn2dsl -t SNSToSQS.template -o SNSToSQS.rb
start cmd.exe /C cfn2dsl -t SQS.template -o SQS.rb
start cmd.exe /C cfn2dsl -t SQSWithQueueName.template -o SQSWithQueueName.rb
start cmd.exe /C cfn2dsl -t SQS_Sample_Base_Producer_Consumer.template -o SQS_Sample_Base_Producer_Consumer.rb
start cmd.exe /C cfn2dsl -t SQS_Sample_Base_Producer_Consumer_x2.template -o SQS_Sample_Base_Producer_Consumer_x2.rb
start cmd.exe /C cfn2dsl -t SQS_Sample_Batch_Producer_Consumer.template -o SQS_Sample_Batch_Producer_Consumer.rb
start cmd.exe /C cfn2dsl -t SQS_With_CloudWatch_Alarms.template -o SQS_With_CloudWatch_Alarms.rb
start cmd.exe /C cfn2dsl -t SampleRailsApp.template -o SampleRailsApp.rb
start cmd.exe /C cfn2dsl -t Templates_within_Templates.template -o Templates_within_Templates.rb
start cmd.exe /C cfn2dsl -t Tracks_Multi_AZ.template -o Tracks_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t Tracks_Simple.template -o Tracks_Simple.rb
start cmd.exe /C cfn2dsl -t Tracks_Single_Instance.template -o Tracks_Single_Instance.rb
start cmd.exe /C cfn2dsl -t Tracks_Single_Instance_With_RDS.template -o Tracks_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t UpdateTutorial -o UpdateTutorial.rb
start cmd.exe /C cfn2dsl -t UpdateTutorial -o UpdateTutorial.rb
start cmd.exe /C cfn2dsl -t UpdateTutorial -o UpdateTutorial.rb
start cmd.exe /C cfn2dsl -t UpdateTutorial -o UpdateTutorial.rb
start cmd.exe /C cfn2dsl -t UpdateTutorial -o UpdateTutorial.rb
start cmd.exe /C cfn2dsl -t UpdateTutorialPart1.template -o UpdateTutorialPart1.rb
start cmd.exe /C cfn2dsl -t UpdateTutorialPart2.template -o UpdateTutorialPart2.rb
start cmd.exe /C cfn2dsl -t UpdateTutorialPart3.template -o UpdateTutorialPart3.rb
start cmd.exe /C cfn2dsl -t UpdateTutorialPart4.template -o UpdateTutorialPart4.rb
start cmd.exe /C cfn2dsl -t UpdateTutorialPart5.template -o UpdateTutorialPart5.rb
start cmd.exe /C cfn2dsl -t VPC_AutoScaling_and_ElasticLoadBalancer.template -o VPC_AutoScaling_and_ElasticLoadBalancer.rb
start cmd.exe /C cfn2dsl -t VPC_EC2_Instance_With_Multiple_Dynamic_IPAddresses.templat -o VPC_EC2_Instance_With_Multiple_Dynamic_IPAddresses.rb
start cmd.exe /C cfn2dsl -t VPC_EC2_Instance_With_Multiple_Static_IPAddresses.template -o VPC_EC2_Instance_With_Multiple_Static_IPAddresses.rb
start cmd.exe /C cfn2dsl -t VPC_EC2_Instance_with_EIP_and_Security_Group.template -o VPC_EC2_Instance_with_EIP_and_Security_Group.rb
start cmd.exe /C cfn2dsl -t VPC_ElastiCache_Cluster.template -o VPC_ElastiCache_Cluster.rb
start cmd.exe /C cfn2dsl -t VPC_Instance_With_Association.template -o VPC_Instance_With_Association.rb
start cmd.exe /C cfn2dsl -t VPC_RDS_DB_Instance.template -o VPC_RDS_DB_Instance.rb
start cmd.exe /C cfn2dsl -t VPC_With_PublicIPs_And_DNS.template -o VPC_With_PublicIPs_And_DNS.rb
start cmd.exe /C cfn2dsl -t VPC_With_VPN_Connection.template -o VPC_With_VPN_Connection.rb
start cmd.exe /C cfn2dsl -t VPC_WordPress_Single_Instance_With_RDS.template -o VPC_WordPress_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t WaitObject.template -o WaitObject.rb
start cmd.exe /C cfn2dsl -t Windows_Roles_And_Features.template -o Windows_Roles_And_Features.rb
start cmd.exe /C cfn2dsl -t Windows_Single_Server_Active_Directory.template -o Windows_Single_Server_Active_Directory.rb
start cmd.exe /C cfn2dsl -t Windows_Single_Server_SharePoint_Foundation.template -o Windows_Single_Server_SharePoint_Foundation.rb
start cmd.exe /C cfn2dsl -t WordPress_Multi_AZ.template -o WordPress_Multi_AZ.rb
start cmd.exe /C cfn2dsl -t WordPress_Simple.template -o WordPress_Simple.rb
start cmd.exe /C cfn2dsl -t WordPress_Single_Instance.template -o WordPress_Single_Instance.rb
start cmd.exe /C cfn2dsl -t WordPress_Single_Instance_With_RDS.template -o WordPress_Single_Instance_With_RDS.rb
start cmd.exe /C cfn2dsl -t auto_scaling_with_instance_profile.template -o auto_scaling_with_instance_profile.rb
start cmd.exe /C cfn2dsl -t bees-with-machineguns.template -o bees-with-machineguns.rb
start cmd.exe /C cfn2dsl -t cc1-cluster.json -o cc1-cluster.rb
start cmd.exe /C cfn2dsl -t cc2-cluster.json -o cc2-cluster.rb
start cmd.exe /C cfn2dsl -t cc2-spot-cluster.template -o cc2-spot-cluster.rb
start cmd.exe /C cfn2dsl -t chef-server-ubuntu-configuration.template -o chef-server-ubuntu-configuration.rb
start cmd.exe /C cfn2dsl -t chef-solo-configuration.template -o chef-solo-configuration.rb
start cmd.exe /C cfn2dsl -t ec2_instance_with_instance_profile.template -o ec2_instance_with_instance_profile.rb
start cmd.exe /C cfn2dsl -t multi-tier-vpc.template -o multi-tier-vpc.rb
start cmd.exe /C cfn2dsl -t multi-tier-web-app-in-vpc.template -o multi-tier-web-app-in-vpc.rb
start cmd.exe /C cfn2dsl -t puppet-client-configuration.template -o puppet-client-configuration.rb
start cmd.exe /C cfn2dsl -t puppet-master-configuration.template -o puppet-master-configuration.rb
start cmd.exe /C cfn2dsl -t sns_httpendpoint.template -o sns_httpendpoint.rb
start cmd.exe /C cfn2dsl -t vpc_multiple_subnets.template -o vpc_multiple_subnets.rb
start cmd.exe /C cfn2dsl -t vpc_single_instance_in_subnet.template -o vpc_single_instance_in_subnet.rb
start cmd.exe /C cfn2dsl -t wordpress-via-cfn-bootstrap.template -o wordpress-via-cfn-bootstrap.rb
start cmd.exe /C cfn2dsl -t wordpress-via-chef-client.template -o wordpress-via-chef-client.rb
start cmd.exe /C cfn2dsl -t wordpress-via-chef-solo-building-block.template -o wordpress-via-chef-solo-building-block.rb
start cmd.exe /C cfn2dsl -t wordpress-via-chef-solo.template -o wordpress-via-chef-solo.rb
start cmd.exe /C cfn2dsl -t wordpress-via-puppet-client-building-block.template -o wordpress-via-puppet-client-building-block.rb
start cmd.exe /C cfn2dsl -t wordpress-via-puppet-client.template -o wordpress-via-puppet-client.rb
start cmd.exe /C cfn2dsl -t worker-role.template -o worker-role.rb
