AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch,
          !Ref 'InstanceType', Arch]]
      KeyName: !Ref 'KeyName'
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'Ec2SecurityGroup']
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: '50'
      - DeviceName: /dev/sdm
        Ebs:
          VolumeSize: '100'
  Ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', PV64]
      KeyName: !Ref 'KeyName'
      InstanceType: m1.small
      SecurityGroups: [!Ref 'Ec2SecurityGroup']
      BlockDeviceMappings:
      - DeviceName: /dev/sdc
        VirtualName: ephemeral0
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref 'logical name of an AWS::EC2::Instance resource'
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'logical name of an AWS::EC2::Instance resource'
      EIP: existing Elastic IP address
  VpcIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'logical name of an AWS::EC2::Instance resource'
      AllocationId: existing VPC Elastic IP allocation ID
  ControlPortAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AssociateControlPort:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt [ControlPortAddress, AllocationId]
      NetworkInterfaceId: !Ref 'controlXface'
  WebPortAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AssociateWebPort:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt [WebPortAddress, AllocationId]
      NetworkInterfaceId: !Ref 'webXface'
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: Enable HTTP access via user defined port
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  controlXface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref 'SubnetId'
      Description: Interface for control traffic such as SSH
      GroupSet: [!Ref 'SSHSecurityGroup']
      SourceDestCheck: 'true'
      Tags:
      - Key: Network
        Value: Control
  webXface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref 'SubnetId'
      Description: Interface for web traffic
      GroupSet: [!Ref 'WebSecurityGroup']
      SourceDestCheck: 'true'
      Tags:
      - Key: Network
        Value: Web
  Ec2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      KeyName: !Ref 'KeyName'
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref 'controlXface'
        DeviceIndex: '0'
      - NetworkInterfaceId: !Ref 'webXface'
        DeviceIndex: '1'
      Tags:
      - Key: Role
        Value: Test Instance
      UserData: !Base64
        Fn::Join:
        - ''
        - ['#!/bin/bash -ex', '

            ', '

            ', yum install ec2-net-utils -y, '

            ', ec2ifup eth1, '

            ', service httpd start]
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-20b65349
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref 'KeyName'
      SecurityGroups: [!Ref 'logical name of AWS::EC2::SecurityGroup resource']
      UserData: !Base64
        Fn::Join:
        - ':'
        - [PORT=80, TOPIC=, !Ref 'logical name of an AWS::SNS::Topic resource']
      InstanceType: m1.small
      AvailabilityZone: us-east-1a
      ImageId: ami-1e817677
      Volumes:
      - VolumeId: !Ref 'logical name of AWS::EC2::Volume resource'
        Device: /dev/sdk
      Tags:
      - Key: Name
        Value: MyTag
  MyInstance3:
    Type: AWS::EC2::Instance
    Properties:
      UserData: !Base64
        Fn::Join:
        - ''
        - [Domain=, !Ref 'logical name of an AWS::SDB::Domain resource']
      AvailabilityZone: us-east-1a
      ImageId: ami-20b65349
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 192.168.1.1/32
  ServerSecurityGroupBySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified source security group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        SourceSecurityGroupName: myadminsecuritygroup
        SourceSecurityGroupOwnerId: '123456789012'
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        SourceSecurityGroupName: !Ref 'mysecuritygroupcreatedincfn'
  myELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: [us-east-1a]
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
  ELBIngressGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB ingress group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        SourceSecurityGroupOwnerId: !GetAtt [myELB, SourceSecurityGroup.OwnerAlias]
        SourceSecurityGroupName: !GetAtt [myELB, SourceSecurityGroup.GroupName]
  SGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Instance access
  SGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Instance access
  SGroup1Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupName: !Ref 'SGroup1'
      IpProtocol: tcp
      ToPort: '80'
      FromPort: '80'
      SourceSecurityGroupName: !Ref 'SGroup2'
  SGroup2Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupName: !Ref 'SGroup2'
      IpProtocol: tcp
      ToPort: '80'
      FromPort: '80'
      SourceSecurityGroupName: !Ref 'SGroup1'
  MyEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: specify a size if no SnapShotId
      SnapshotId: specify a SnapShotId if no Size
      AvailabilityZone: !Ref 'AvailabilityZone'
    DeletionPolicy: Snapshot
  Ec2Instance4:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      ImageId: ami-76f0061f
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  NewVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: '100'
      AvailabilityZone: !GetAtt [Ec2Instance, AvailabilityZone]
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref 'Ec2Instance'
      VolumeId: !Ref 'NewVolume'
      Device: /dev/sdh
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref 'myVPCCIDRRange'
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default
  myInstance5:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', '64']
      SecurityGroupIds:
      - !GetAtt [myVPC, DefaultSecurityGroup]
      SubnetId: !Ref 'mySubnet'
